/*
  # Create recipes table with sample data

  1. New Tables
    - `recipes`
      - `id` (bigint, primary key)
      - `title` (text)
      - `making_time` (text)
      - `serves` (text)
      - `ingredients` (text)
      - `cost` (integer)
      - `created_at` (timestamptz)
      - `updated_at` (timestamptz)

  2. Security
    - Enable RLS on `recipes` table
    - Add policy for public read access
*/

CREATE TABLE recipes (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  making_time text NOT NULL,
  serves text NOT NULL,
  ingredients text NOT NULL,
  cost integer NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
  ON recipes
  FOR SELECT
  TO public
  USING (true);

-- Insert sample data
INSERT INTO recipes (title, making_time, serves, ingredients, cost, created_at, updated_at)
VALUES
  (
    'Chicken Curry',
    '45 min',
    '4 people',
    'onion, chicken, seasoning',
    1000,
    '2016-01-10 12:10:12',
    '2016-01-10 12:10:12'
  ),
  (
    'Rice Omelette',
    '30 min',
    '2 people',
    'onion, egg, seasoning, soy sauce',
    700,
    '2016-01-11 13:10:12',
    '2016-01-11 13:10:12'
  );